<?php

use Illuminate\Database\Seeder;

class SeekerProfileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::table('seeker_profile')->insert(array(
        //     array('user_id'=>1),
        //     array('user_id'=>2),
        //     array('user_id'=>3),
        //     array('user_id'=>4),
        //     array('user_id'=>5),
        //     array('user_id'=>6),
        //     array('user_id'=>7),
        //     array('user_id'=>8),
        //     array('user_id'=>9),
        //     array('user_id'=>10),
        //     array('user_id'=>11),
        //     array('user_id'=>12),
        //     array('user_id'=>13),
        //     array('user_id'=>14),
        //     array('user_id'=>15),
        //     array('user_id'=>16),
        //     array('user_id'=>17),
        //     array('user_id'=>18),
        //     array('user_id'=>19),
        //     array('user_id'=>20),
        //     array('user_id'=>21),
        //     array('user_id'=>22),
        //     array('user_id'=>23),
        //     array('user_id'=>24),
        //     array('user_id'=>25),
        //     array('user_id'=>26),
        //     array('user_id'=>27),
        //     array('user_id'=>28),
        //     array('user_id'=>29),
        //     array('user_id'=>30),
        //     array('user_id'=>31),
        //     array('user_id'=>32),
        //     array('user_id'=>33),
        //     array('user_id'=>34),
        //     array('user_id'=>35),
        //     array('user_id'=>36),
        //     array('user_id'=>37),
        //     array('user_id'=>38),
        //     array('user_id'=>39),
        //     array('user_id'=>40),
        //     array('user_id'=>41),
        //     array('user_id'=>42),
        //     array('user_id'=>43),
        //     array('user_id'=>44),
        //     array('user_id'=>45),
        //     array('user_id'=>46),
        //     array('user_id'=>47),
        //     array('user_id'=>48),
        //     array('user_id'=>49),
        //     array('user_id'=>50),
        //     array('user_id'=>51),
        //     array('user_id'=>52),
        //     array('user_id'=>53),
        //     array('user_id'=>54),
        //     array('user_id'=>55),
        //     array('user_id'=>56),
        //     array('user_id'=>57),
        //     array('user_id'=>58),
        //     array('user_id'=>59),
        //     array('user_id'=>60),
        //     array('user_id'=>61),
        //     array('user_id'=>62),
        //     array('user_id'=>63),
        //     array('user_id'=>64),
        //     array('user_id'=>65),
        //     array('user_id'=>66),
        //     array('user_id'=>67),
        //     array('user_id'=>68),
        //     array('user_id'=>69),
        //     array('user_id'=>70),
        //     array('user_id'=>71),
        //     array('user_id'=>72),
        //     array('user_id'=>73),
        //     array('user_id'=>74),
        //     array('user_id'=>75),
        //     array('user_id'=>76),
        //     array('user_id'=>77),
        //     array('user_id'=>78),
        //     array('user_id'=>79),
        //     array('user_id'=>80),
        //     array('user_id'=>81),
        //     array('user_id'=>82),
        //     array('user_id'=>83),
        //     array('user_id'=>84),
        //     array('user_id'=>85),
        //     array('user_id'=>86),
        //     array('user_id'=>87),
        //     array('user_id'=>88),
        //     array('user_id'=>89),
        //     array('user_id'=>90),
        //     array('user_id'=>91),
        //     array('user_id'=>92),
        //     array('user_id'=>93),
        //     array('user_id'=>94),
        //     array('user_id'=>95),
        //     array('user_id'=>96),
        //     array('user_id'=>97),
        //     array('user_id'=>98),
        //     array('user_id'=>99),
        //     array('user_id'=>100),
        // ));
        factory('App\SeekerProfile', 100)->create();
    }
}
