<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\ExperienceDetails;
use Faker\Generator as Faker;

$factory->define(ExperienceDetails::class, function (Faker $faker) {
    return [
        'seeker_profile_id'=> $faker->numberBetween(1,100),
        'company_name'=>$faker->company,
        'job_title' =>$faker->randomElement(['Computer Scientist',
        'IT Professional',
        'UX Designer & UI Developer',
        'SQL Developer',
        'Web Designer',
        'Web Developer',
        'Help Desk Worker/Desktop Support',
        'Software Engineer',
        'Data Entry',
        'DevOps Engineer',
        'Computer Programmer',
        'Network Administrator',
        'Information Security Analyst',
        'Artificial Intelligence Engineer',
        'Cloud Architect',
        'IT Manager',
        'Technical Specialist',
        'Application Developer',
        'Chief Technology Officer (CTO)',
        'Chief Information Officer (CIO)'
    ]),
    'start_date'=>$faker->date($format = 'Y-m-d',$max='2019-12-31'),
    'end_date'=>$faker->date($format = 'Y-m-d',$max='2019-12-31'),
    'website'=>$faker->url,
    'job_location_city'=>$faker->city,
    'job_location_county'=>$faker->randomElement([
            'MOMBASA',
            'KWALE',
            'KILIFI',
           'TANA RIVER',
            'LAMU',
           'TAITA TAVETA',
            'GARISSA',
            'WAJIR',
            'MANDERA',
           'MARSABIT',   
           'ISIOLO',   
           'MERU',   
           'THARAKA-NITHI',   
           'EMBU',   
           'KITUI',   
           'MACHAKOS',   
           'MAKUENI',   
           'NYANDARUA',   
           'NYERI',   
           'KIRINYAGA',   
           'MURANGA',   
           'KIAMBU',   
           'TURKANA',   
           'WEST POKOT',   
           'SAMBURU',   
           'TRANS NZOIA',   
           'UASIN GISHU',   
           'ELGEYO/MARAKWET',   
           'NANDI',   
           'BARINGO',   
           'LAIKIPIA',   
           'NAKURU',   
           'NAROK',   
           'KAJIADO',   
           'KERICHO',   
           'BOMET',   
           'KAKAMEGA',   
           'VIHIGA',   
           'BUNGOMA',   
           'BUSIA',   
           'SIAYA',   
           'KISUMU',   
           'HOMA BAY',   
           'MIGORI',   
           'KISII',   
           'NYAMIRA',   
           'NAIROBI',    
    ]),
    'job_location_country'=>'Kenya'
    ];
});
